## Numpy Stands for Numerical Python
Python has actually a list but it is very slow thats why numpy arrays used which are 50x faster than list. 

In [1]:
import numpy as np

In [2]:
# create arr
arr = np.array([1,2,3,4,50])
arr2 = np.array([[1,2],[2,3],[4,5]])
print(arr, type(arr), arr2.shape)

[ 1  2  3  4 50] <class 'numpy.ndarray'> (3, 2)


In [3]:
zeros_array = np.zeros((2,2))

ones_array = np.ones((2,2))
print(zeros_array, ones_array)



[[0. 0.]
 [0. 0.]] [[1. 1.]
 [1. 1.]]


In [4]:
print(arr2[0,:])

[1 2]


In [5]:
print(arr2**2)

[[ 1  4]
 [ 4  9]
 [16 25]]


In [6]:
print(arr2.transpose())

[[1 2 4]
 [2 3 5]]


In [7]:
print(arr.mean(), np.median(arr))

12.0 3.0
